// @generated by minco-contract 1.12.0
// Contract SHA-256: 57751e6fbe59fb79ba11899f767f194a1853e1188e670bf8ad731e81c1558757
// Do not edit manually; run `minco contract sync`.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_variables, clippy::struct_excessive_bools)]
#[allow(unused_imports)]
use chrono::{DateTime, Utc};
use minco_contract::ContractAuthorizationAlternative;
use minco_contract::{
    ContractAuthorizationPolicy, ContractOperation, ContractValidate, ContractValidationErrors,
    HttpMethod, deserialize_optional_non_null,
};
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentBootstrap {
    pub brand: String,
    pub capabilities: serde_json::Value,
    pub label: String,
    pub project_id: String,
    pub schema_version: i64,
    pub subject: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AgentCuratedView {
    #[serde(rename = "new-unassigned")]
    NewUnassigned,
    #[serde(rename = "pending-requester")]
    PendingRequester,
    #[serde(rename = "pending-internal")]
    PendingInternal,
    #[serde(rename = "mine")]
    Mine,
    #[serde(rename = "recently-resolved")]
    RecentlyResolved,
}

impl ContractValidate for AgentCuratedView {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentMacro {
    pub body: String,
    pub id: Uuid,
    pub revision: i64,
    pub title: String,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentMacroCollection {
    pub data: Vec<AgentMacro>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentMacroMutation {
    #[serde(rename = "macro")]
    pub r#macro: AgentMacro,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentManagement {
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub assignee_subject: Option<String>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub clear_assignee: Option<bool>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub close_reason: Option<String>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub priority: Option<TicketPriority>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub queue_id: Option<String>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub resolution: Option<String>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<TicketStatus>,
}

impl ContractValidate for AgentManagement {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.assignee_subject {
            errors.at_field("assignee_subject", |errors| {
                let character_count = value.chars().count();
                if character_count > 300 {
                    errors.add("must contain no more than 300 characters");
                }
            });
        }
        if let Some(value) = &self.clear_assignee {
            errors.at_field("clear_assignee", |errors| {
            });
        }
        if let Some(value) = &self.close_reason {
            errors.at_field("close_reason", |errors| {
                let character_count = value.chars().count();
                if character_count > 500 {
                    errors.add("must contain no more than 500 characters");
                }
            });
        }
        if let Some(value) = &self.priority {
            errors.at_field("priority", |errors| {
            });
        }
        if let Some(value) = &self.queue_id {
            errors.at_field("queue_id", |errors| {
                let character_count = value.chars().count();
                if character_count > 200 {
                    errors.add("must contain no more than 200 characters");
                }
            });
        }
        if let Some(value) = &self.resolution {
            errors.at_field("resolution", |errors| {
                let character_count = value.chars().count();
                if character_count > 20000 {
                    errors.add("must contain no more than 20000 characters");
                }
            });
        }
        if let Some(value) = &self.status {
            errors.at_field("status", |errors| {
            });
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentTicketDetail {
    pub other_recent_viewers: Vec<String>,
    pub ticket: Ticket,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AttachmentKind {
    #[serde(rename = "screenshot")]
    Screenshot,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "file")]
    File,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AttachmentLimits {
    pub aggregate_bytes: i64,
    pub audio_bytes: i64,
    pub count: i64,
    pub file_bytes: i64,
    pub screenshot_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutomationAccepted {
    pub correlation_id: Uuid,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutomationDecision {
    pub decision: AutomationDecisionKind,
}

impl ContractValidate for AutomationDecision {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("decision", |errors| {
            let value = &self.decision;
        });
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AutomationDecisionKind {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "reject")]
    Reject,
}

impl ContractValidate for AutomationDecisionKind {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutomationProposal {
    pub created_at: DateTime<Utc>,
    pub created_by: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decided_at: Option<DateTime<Utc>>,
    pub id: Uuid,
    pub requested_actions: Vec<String>,
    pub state: String,
    pub summary: String,
    pub ticket_id: Uuid,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutomationProposalCollection {
    pub data: Vec<AutomationProposal>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutomationProposalMutation {
    pub proposal: AutomationProposal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Clarification {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checkpoint: Option<String>,
    pub created_at: DateTime<Utc>,
    pub created_by: String,
    pub id: Uuid,
    pub questions: Vec<ClarificationQuestion>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<DateTime<Utc>>,
    pub state: ClarificationState,
    pub ticket_id: Uuid,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClarificationCollection {
    pub data: Vec<Clarification>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClarificationMutation {
    pub clarification: Clarification,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClarificationQuestion {
    pub id: String,
    pub text: String,
}

impl ContractValidate for ClarificationQuestion {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("id", |errors| {
            let value = &self.id;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 64 {
                errors.add("must contain no more than 64 characters");
            }
        });
        errors.at_field("text", |errors| {
            let value = &self.text;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 2000 {
                errors.add("must contain no more than 2000 characters");
            }
        });
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ClarificationState {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "answered")]
    Answered,
    #[serde(rename = "withdrawn")]
    Withdrawn,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsumedHandoff {
    pub repeated: bool,
    pub result: serde_json::Value,
    pub ticket: RequesterTicket,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CreateAgentMacro {
    pub body: String,
    pub title: String,
}

impl ContractValidate for CreateAgentMacro {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("body", |errors| {
            let value = &self.body;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
        errors.at_field("title", |errors| {
            let value = &self.title;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CreateClarification {
    pub checkpoint: String,
    pub questions: Vec<ClarificationQuestion>,
    pub reason: String,
}

impl ContractValidate for CreateClarification {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("checkpoint", |errors| {
            let value = &self.checkpoint;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 500 {
                errors.add("must contain no more than 500 characters");
            }
        });
        errors.at_field("questions", |errors| {
            let value = &self.questions;
            if value.is_empty() {
                errors.add("must contain at least 1 item");
            }
            if value.len() > 8 {
                errors.add("must contain no more than 8 items");
            }
            for (index, item) in value.iter().take(8).enumerate() {
                if errors.is_truncated() {
                    break;
                }
                errors.at_index(index, |errors| {
                    item.validate_contract(errors);
                });
            }
        });
        errors.at_field("reason", |errors| {
            let value = &self.reason;
            if !(value.as_str() == "missing_requirement" || value.as_str() == "contradictory_requirement") {
                errors.add("must be an allowed value");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CreateTicket {
    pub channel: TicketChannel,
    pub description: String,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub form_answers: Option<Vec<TicketFormAnswer>>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub priority: Option<TicketPriority>,
    pub project_id: String,
    pub requester: TicketRequester,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_references: Option<Vec<ResourceReference>>,
    pub subject: String,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub ticket_type: Option<TicketType>,
}

impl ContractValidate for CreateTicket {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("channel", |errors| {
            let value = &self.channel;
        });
        errors.at_field("description", |errors| {
            let value = &self.description;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
        if let Some(value) = &self.form_answers {
            errors.at_field("form_answers", |errors| {
                if value.len() > 16 {
                    errors.add("must contain no more than 16 items");
                }
                for (index, item) in value.iter().take(16).enumerate() {
                    if errors.is_truncated() {
                        break;
                    }
                    errors.at_index(index, |errors| {
                        item.validate_contract(errors);
                    });
                }
            });
        }
        if let Some(value) = &self.priority {
            errors.at_field("priority", |errors| {
            });
        }
        errors.at_field("project_id", |errors| {
            let value = &self.project_id;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
        errors.at_field("requester", |errors| {
            let value = &self.requester;
            value.validate_contract(errors);
        });
        if let Some(value) = &self.resource_references {
            errors.at_field("resource_references", |errors| {
                if value.len() > 32 {
                    errors.add("must contain no more than 32 items");
                }
                for (index, item) in value.iter().take(32).enumerate() {
                    if errors.is_truncated() {
                        break;
                    }
                    errors.at_index(index, |errors| {
                        item.validate_contract(errors);
                    });
                }
            });
        }
        errors.at_field("subject", |errors| {
            let value = &self.subject;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        if let Some(value) = &self.ticket_type {
            errors.at_field("ticket_type", |errors| {
            });
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExchangeHandoff {
    pub channel: TicketChannel,
    pub description: String,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub form_answers: Option<Vec<TicketFormAnswer>>,
    pub portal_origin: String,
    pub priority: TicketPriority,
    pub project_id: String,
    pub subject: String,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub ticket_type: Option<TicketType>,
}

impl ContractValidate for ExchangeHandoff {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("channel", |errors| {
            let value = &self.channel;
        });
        errors.at_field("description", |errors| {
            let value = &self.description;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
        if let Some(value) = &self.form_answers {
            errors.at_field("form_answers", |errors| {
                if value.len() > 16 {
                    errors.add("must contain no more than 16 items");
                }
                for (index, item) in value.iter().take(16).enumerate() {
                    if errors.is_truncated() {
                        break;
                    }
                    errors.at_index(index, |errors| {
                        item.validate_contract(errors);
                    });
                }
            });
        }
        errors.at_field("portal_origin", |errors| {
            let value = &self.portal_origin;
        });
        errors.at_field("priority", |errors| {
            let value = &self.priority;
        });
        errors.at_field("project_id", |errors| {
            let value = &self.project_id;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
        errors.at_field("subject", |errors| {
            let value = &self.subject;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        if let Some(value) = &self.ticket_type {
            errors.at_field("ticket_type", |errors| {
            });
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IngressMessage {
    pub body: String,
    pub content_sha256: String,
    pub external_message_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internet_message_id: Option<String>,
    pub mailbox_scope: String,
    pub provider: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw_message_object_key: Option<String>,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub references: Option<Vec<String>>,
    pub ticket_id: Uuid,
}

impl ContractValidate for IngressMessage {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("body", |errors| {
            let value = &self.body;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
        errors.at_field("content_sha256", |errors| {
            let value = &self.content_sha256;
            let character_count = value.chars().count();
            if character_count < 64 {
                errors.add("must contain at least 64 characters");
            }
            if character_count > 64 {
                errors.add("must contain no more than 64 characters");
            }
        });
        errors.at_field("external_message_id", |errors| {
            let value = &self.external_message_id;
            let character_count = value.chars().count();
            if character_count > 500 {
                errors.add("must contain no more than 500 characters");
            }
        });
        if let Some(value) = &self.in_reply_to {
            errors.at_field("in_reply_to", |errors| {
                let character_count = value.chars().count();
                if character_count > 1000 {
                    errors.add("must contain no more than 1000 characters");
                }
            });
        }
        if let Some(value) = &self.internet_message_id {
            errors.at_field("internet_message_id", |errors| {
                let character_count = value.chars().count();
                if character_count > 1000 {
                    errors.add("must contain no more than 1000 characters");
                }
            });
        }
        errors.at_field("mailbox_scope", |errors| {
            let value = &self.mailbox_scope;
            let character_count = value.chars().count();
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        errors.at_field("provider", |errors| {
            let value = &self.provider;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
        if let Some(value) = &self.raw_message_object_key {
            errors.at_field("raw_message_object_key", |errors| {
                let character_count = value.chars().count();
                if character_count > 1000 {
                    errors.add("must contain no more than 1000 characters");
                }
            });
        }
        if let Some(value) = &self.references {
            errors.at_field("references", |errors| {
                if value.len() > 64 {
                    errors.add("must contain no more than 64 items");
                }
                for (index, item) in value.iter().take(64).enumerate() {
                    if errors.is_truncated() {
                        break;
                    }
                    errors.at_index(index, |errors| {
                        let character_count = item.chars().count();
                        if character_count > 1000 {
                            errors.add("must contain no more than 1000 characters");
                        }
                    });
                }
            });
        }
        errors.at_field("ticket_id", |errors| {
            let value = &self.ticket_id;
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IssueHandoff {
    pub context: SupportContext,
    pub project_id: String,
    pub requester_permissions: Vec<String>,
    pub requester_subject: String,
    pub return_location: String,
    pub surface: SupportSurface,
}

impl ContractValidate for IssueHandoff {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("context", |errors| {
            let value = &self.context;
            value.validate_contract(errors);
        });
        errors.at_field("project_id", |errors| {
            let value = &self.project_id;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
        errors.at_field("requester_permissions", |errors| {
            let value = &self.requester_permissions;
            if value.len() > 64 {
                errors.add("must contain no more than 64 items");
            }
            for (index, item) in value.iter().take(64).enumerate() {
                if errors.is_truncated() {
                    break;
                }
                errors.at_index(index, |errors| {
                    let character_count = item.chars().count();
                    if character_count > 160 {
                        errors.add("must contain no more than 160 characters");
                    }
                });
            }
        });
        errors.at_field("requester_subject", |errors| {
            let value = &self.requester_subject;
            let character_count = value.chars().count();
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        errors.at_field("return_location", |errors| {
            let value = &self.return_location;
            let character_count = value.chars().count();
            if character_count > 2000 {
                errors.add("must contain no more than 2000 characters");
            }
        });
        errors.at_field("surface", |errors| {
            let value = &self.surface;
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IssuedHandoff {
    pub expires_at: DateTime<Utc>,
    pub launch_url: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct KnowledgeLink {
    pub article_id: String,
    pub title: String,
    pub url: String,
}

impl ContractValidate for KnowledgeLink {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("article_id", |errors| {
            let value = &self.article_id;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 200 {
                errors.add("must contain no more than 200 characters");
            }
        });
        errors.at_field("title", |errors| {
            let value = &self.title;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        errors.at_field("url", |errors| {
            let value = &self.url;
            let character_count = value.chars().count();
            if character_count < 8 {
                errors.add("must contain at least 8 characters");
            }
            if character_count > 2048 {
                errors.add("must contain no more than 2048 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct KnowledgeLinks {
    pub links: Vec<KnowledgeLink>,
}

impl ContractValidate for KnowledgeLinks {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("links", |errors| {
            let value = &self.links;
            if value.len() > 16 {
                errors.add("must contain no more than 16 items");
            }
            for (index, item) in value.iter().take(16).enumerate() {
                if errors.is_truncated() {
                    break;
                }
                errors.at_index(index, |errors| {
                    item.validate_contract(errors);
                });
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProblemDetails {
    pub code: String,
    pub detail: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub errors: Option<serde_json::Value>,
    #[serde(rename = "requestId")]
    pub request_id: String,
    pub status: i64,
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReplyClarification {
    pub answers: Vec<String>,
}

impl ContractValidate for ReplyClarification {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("answers", |errors| {
            let value = &self.answers;
            if value.is_empty() {
                errors.add("must contain at least 1 item");
            }
            if value.len() > 8 {
                errors.add("must contain no more than 8 items");
            }
            for (index, item) in value.iter().take(8).enumerate() {
                if errors.is_truncated() {
                    break;
                }
                errors.at_index(index, |errors| {
                    let character_count = item.chars().count();
                    if character_count < 1 {
                        errors.add("must contain at least 1 characters");
                    }
                    if character_count > 4000 {
                        errors.add("must contain no more than 4000 characters");
                    }
                });
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterAttachment {
    pub content_type: String,
    pub created_at: DateTime<Utc>,
    pub file_name: String,
    pub id: Uuid,
    pub kind: AttachmentKind,
    pub size_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterClarification {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<String>>,
    pub created_at: DateTime<Utc>,
    pub id: Uuid,
    pub questions: Vec<ClarificationQuestion>,
    pub state: String,
    pub ticket_id: Uuid,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterClarificationCollection {
    pub data: Vec<RequesterClarification>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterClarificationMutation {
    pub clarification: RequesterClarification,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterCsat {
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub comment: Option<String>,
    pub score: i64,
}

impl ContractValidate for RequesterCsat {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.comment {
            errors.at_field("comment", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        errors.at_field("score", |errors| {
            let value = &self.score;
            if i128::from(*value) < 1 {
                errors.add("must be greater than or equal to 1");
            }
            if i128::from(*value) > 5 {
                errors.add("must be less than or equal to 5");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterMessage {
    pub author: String,
    pub body: String,
    pub created_at: DateTime<Utc>,
    pub id: Uuid,
    pub kind: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RequesterStatus {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "waiting_for_you")]
    WaitingForYou,
    #[serde(rename = "on_hold")]
    OnHold,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "closed")]
    Closed,
}

impl ContractValidate for RequesterStatus {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterTicket {
    pub attachments: Vec<RequesterAttachment>,
    pub channel: TicketChannel,
    pub created_at: DateTime<Utc>,
    pub csat: TicketCsat,
    pub description: String,
    pub display_reference: String,
    pub form_answers: Vec<TicketFormAnswer>,
    pub id: Uuid,
    pub messages: Vec<RequesterMessage>,
    pub priority: TicketPriority,
    pub project_id: String,
    pub requester: TicketRequester,
    pub revision: i64,
    pub status: RequesterStatus,
    pub subject: String,
    pub ticket_type: TicketType,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterTicketMutation {
    pub ticket: RequesterTicket,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<TicketWarning>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RequesterTicketSummary {
    pub display_reference: String,
    pub id: Uuid,
    pub message_count: i64,
    pub needs_attention: bool,
    pub revision: i64,
    pub status: RequesterStatus,
    pub subject: String,
    pub ticket_type: TicketType,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResourceReference {
    pub resource_id: String,
    pub resource_type: String,
    pub system: String,
}

impl ContractValidate for ResourceReference {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("resource_id", |errors| {
            let value = &self.resource_id;
            let character_count = value.chars().count();
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
        errors.at_field("resource_type", |errors| {
            let value = &self.resource_type;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
        errors.at_field("system", |errors| {
            let value = &self.system;
            let character_count = value.chars().count();
            if character_count > 100 {
                errors.add("must contain no more than 100 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionExchange {
    pub portal_origin: String,
}

impl ContractValidate for SessionExchange {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("portal_origin", |errors| {
            let value = &self.portal_origin;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionGrant {
    pub csrf_token: String,
    pub expires_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceReference {
    pub external_id: String,
    pub provider: String,
    pub scope: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SupportBootstrap {
    pub attachment_limits: AttachmentLimits,
    pub brand: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<SupportCapabilities>,
    pub enabled_surfaces: Vec<SupportSurface>,
    pub file_enabled: bool,
    pub label: String,
    pub portal_origin: String,
    pub privacy_notice: String,
    pub project_id: String,
    pub recording_limit: i64,
    pub schema_version: i64,
    pub screenshot_enabled: bool,
    pub voice_enabled: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SupportCapabilities {
    pub automation: bool,
    pub email: bool,
    pub files: bool,
    pub history: bool,
    pub knowledge: bool,
    pub portal_sessions: bool,
    pub screenshots: bool,
    pub voice: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SupportContext {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_locale: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_page_title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_release_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_request_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_route_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_selected_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_timezone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional_viewport: Option<String>,
    pub page_url: String,
    #[serde(
        default,
        deserialize_with = "deserialize_optional_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_references: Option<Vec<ResourceReference>>,
}

impl ContractValidate for SupportContext {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.optional_locale {
            errors.at_field("optional_locale", |errors| {
                let character_count = value.chars().count();
                if character_count > 40 {
                    errors.add("must contain no more than 40 characters");
                }
            });
        }
        if let Some(value) = &self.optional_page_title {
            errors.at_field("optional_page_title", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        if let Some(value) = &self.optional_release_id {
            errors.at_field("optional_release_id", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        if let Some(value) = &self.optional_request_id {
            errors.at_field("optional_request_id", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        if let Some(value) = &self.optional_route_name {
            errors.at_field("optional_route_name", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        if let Some(value) = &self.optional_selected_text {
            errors.at_field("optional_selected_text", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
        if let Some(value) = &self.optional_timezone {
            errors.at_field("optional_timezone", |errors| {
                let character_count = value.chars().count();
                if character_count > 100 {
                    errors.add("must contain no more than 100 characters");
                }
            });
        }
        if let Some(value) = &self.optional_viewport {
            errors.at_field("optional_viewport", |errors| {
                let character_count = value.chars().count();
                if character_count > 15 {
                    errors.add("must contain no more than 15 characters");
                }
            });
        }
        errors.at_field("page_url", |errors| {
            let value = &self.page_url;
            let character_count = value.chars().count();
            if character_count > 4096 {
                errors.add("must contain no more than 4096 characters");
            }
        });
        if let Some(value) = &self.resource_references {
            errors.at_field("resource_references", |errors| {
                if value.len() > 8 {
                    errors.add("must contain no more than 8 items");
                }
                for (index, item) in value.iter().take(8).enumerate() {
                    if errors.is_truncated() {
                        break;
                    }
                    errors.at_index(index, |errors| {
                        item.validate_contract(errors);
                    });
                }
            });
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SupportSurface {
    #[serde(rename = "widget")]
    Widget,
    #[serde(rename = "portal")]
    Portal,
    #[serde(rename = "extension")]
    Extension,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "mobile")]
    Mobile,
}

impl ContractValidate for SupportSurface {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Ticket {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assignee_subject: Option<String>,
    pub attachments: Vec<TicketAttachment>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    pub channel: TicketChannel,
    pub clock_state: TicketClockState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub close_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub csat: TicketCsat,
    pub description: String,
    pub display_reference: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_public_response_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_response_deadline: Option<DateTime<Utc>>,
    pub followers: Vec<String>,
    pub form_answers: Vec<TicketFormAnswer>,
    pub id: Uuid,
    pub knowledge_links: Vec<KnowledgeLink>,
    pub messages: Vec<TicketMessage>,
    pub priority: TicketPriority,
    pub project_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<String>,
    pub requester: TicketRequester,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution_deadline: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<DateTime<Utc>>,
    pub resource_references: Vec<ResourceReference>,
    pub revision: i64,
    pub source_references: Vec<SourceReference>,
    pub status: TicketStatus,
    pub subject: String,
    pub tags: Vec<String>,
    pub ticket_type: TicketType,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waiting_since: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketAiContext {
    pub description: String,
    pub display_reference: String,
    pub messages: Vec<TicketMessage>,
    pub priority: TicketPriority,
    pub project_id: String,
    pub resource_references: Vec<ResourceReference>,
    pub schema_version: i64,
    pub status: TicketStatus,
    pub subject: String,
    pub ticket_id: Uuid,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketAssignment {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assignee_subject: Option<String>,
    pub mode: TicketAssignmentMode,
}

impl ContractValidate for TicketAssignment {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.assignee_subject {
            errors.at_field("assignee_subject", |errors| {
                let character_count = value.chars().count();
                if character_count > 300 {
                    errors.add("must contain no more than 300 characters");
                }
            });
        }
        errors.at_field("mode", |errors| {
            let value = &self.mode;
        });
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketAssignmentMode {
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "round_robin")]
    RoundRobin,
    #[serde(rename = "least_workload")]
    LeastWorkload,
}

impl ContractValidate for TicketAssignmentMode {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketAttachment {
    pub content_type: String,
    pub created_at: DateTime<Utc>,
    pub file_name: String,
    pub id: Uuid,
    pub kind: AttachmentKind,
    pub object_key: String,
    pub sha256: String,
    pub size_bytes: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketChannel {
    #[serde(rename = "portal")]
    Portal,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "voice")]
    Voice,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "other")]
    Other,
}

impl ContractValidate for TicketChannel {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketClockState {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "stopped")]
    Stopped,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketCollection {
    pub data: Vec<Ticket>,
    pub page: serde_json::Value,
}

pub type TicketCsat = Option<serde_json::Value>;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketFormAnswer {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub boolean_value: Option<bool>,
    pub field_id: String,
    pub kind: TicketFormValueKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub number_value: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text_value: Option<String>,
}

impl ContractValidate for TicketFormAnswer {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.boolean_value {
            errors.at_field("boolean_value", |errors| {
            });
        }
        errors.at_field("field_id", |errors| {
            let value = &self.field_id;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 64 {
                errors.add("must contain no more than 64 characters");
            }
        });
        errors.at_field("kind", |errors| {
            let value = &self.kind;
        });
        if let Some(value) = &self.number_value {
            errors.at_field("number_value", |errors| {
            });
        }
        if let Some(value) = &self.text_value {
            errors.at_field("text_value", |errors| {
                let character_count = value.chars().count();
                if character_count > 2000 {
                    errors.add("must contain no more than 2000 characters");
                }
            });
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketFormValueKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "date_time")]
    DateTime,
}

impl ContractValidate for TicketFormValueKind {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author_subject: Option<String>,
    pub body: String,
    pub created_at: DateTime<Utc>,
    pub direction: TicketMessageDirection,
    pub id: Uuid,
    pub kind: TicketMessageKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketMessageDirection {
    #[serde(rename = "inbound")]
    Inbound,
    #[serde(rename = "outbound")]
    Outbound,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "system")]
    System,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketMessageKind {
    #[serde(rename = "public_reply")]
    PublicReply,
    #[serde(rename = "internal_note")]
    InternalNote,
    #[serde(rename = "system_event")]
    SystemEvent,
    #[serde(rename = "voice_transcript")]
    VoiceTranscript,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketMutation {
    pub ticket: Ticket,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<TicketWarning>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketPriority {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "urgent")]
    Urgent,
}

impl ContractValidate for TicketPriority {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketPriorityChange {
    pub priority: TicketPriority,
}

impl ContractValidate for TicketPriorityChange {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("priority", |errors| {
            let value = &self.priority;
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketQueueTransfer {
    pub queue_id: String,
}

impl ContractValidate for TicketQueueTransfer {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("queue_id", |errors| {
            let value = &self.queue_id;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 200 {
                errors.add("must contain no more than 200 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketReply {
    pub body: String,
}

impl ContractValidate for TicketReply {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("body", |errors| {
            let value = &self.body;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketRequester {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    pub subject: String,
}

impl ContractValidate for TicketRequester {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.display_name {
            errors.at_field("display_name", |errors| {
                let character_count = value.chars().count();
                if character_count > 300 {
                    errors.add("must contain no more than 300 characters");
                }
            });
        }
        if let Some(value) = &self.email {
            errors.at_field("email", |errors| {
                let character_count = value.chars().count();
                if character_count > 320 {
                    errors.add("must contain no more than 320 characters");
                }
            });
        }
        errors.at_field("subject", |errors| {
            let value = &self.subject;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketStatus {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "pending_requester")]
    PendingRequester,
    #[serde(rename = "pending_internal")]
    PendingInternal,
    #[serde(rename = "on_hold")]
    OnHold,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "closed")]
    Closed,
}

impl ContractValidate for TicketStatus {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketStatusChange {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub close_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    pub status: TicketStatus,
}

impl ContractValidate for TicketStatusChange {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        if let Some(value) = &self.close_reason {
            errors.at_field("close_reason", |errors| {
                let character_count = value.chars().count();
                if character_count > 500 {
                    errors.add("must contain no more than 500 characters");
                }
            });
        }
        if let Some(value) = &self.resolution {
            errors.at_field("resolution", |errors| {
                let character_count = value.chars().count();
                if character_count > 20000 {
                    errors.add("must contain no more than 20000 characters");
                }
            });
        }
        errors.at_field("status", |errors| {
            let value = &self.status;
        });
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketSummary {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assignee_subject: Option<String>,
    pub attachment_count: i64,
    pub clock_state: TicketClockState,
    pub created_at: DateTime<Utc>,
    pub display_reference: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_response_deadline: Option<DateTime<Utc>>,
    pub id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_activity_at: Option<DateTime<Utc>>,
    pub message_count: i64,
    pub needs_attention: bool,
    pub priority: TicketPriority,
    pub project_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<String>,
    pub requester_subject: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution_deadline: Option<DateTime<Utc>>,
    pub revision: i64,
    pub status: TicketStatus,
    pub subject: String,
    pub ticket_type: TicketType,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketSummaryCollection {
    pub data: Vec<TicketSummary>,
    pub page: serde_json::Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TicketType {
    #[serde(rename = "question")]
    Question,
    #[serde(rename = "incident")]
    Incident,
    #[serde(rename = "problem")]
    Problem,
    #[serde(rename = "task")]
    Task,
}

impl ContractValidate for TicketType {
    fn validate_contract(&self, _errors: &mut ContractValidationErrors) {}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TicketWarning {
    pub code: String,
    pub detail: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateAgentMacro {
    pub body: String,
    pub title: String,
}

impl ContractValidate for UpdateAgentMacro {
    fn validate_contract(&self, errors: &mut ContractValidationErrors) {
        errors.at_field("body", |errors| {
            let value = &self.body;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 20000 {
                errors.add("must contain no more than 20000 characters");
            }
        });
        errors.at_field("title", |errors| {
            let value = &self.title;
            let character_count = value.chars().count();
            if character_count < 1 {
                errors.add("must contain at least 1 characters");
            }
            if character_count > 300 {
                errors.add("must contain no more than 300 characters");
            }
        });
    }
}

#[rustfmt::skip]
pub const ADD_TICKET_INTERNAL_NOTE: ContractOperation = ContractOperation::new(
    "addTicketInternalNote",
    HttpMethod::Post,
    "/_minco/ticketing/tickets/{ticketId}/internal-notes",
    true,
    false,
);

#[rustfmt::skip]
pub const ADD_TICKET_INTERNAL_NOTE_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "addTicketInternalNote",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CHANGE_TICKET_ASSIGNMENT: ContractOperation = ContractOperation::new(
    "changeTicketAssignment",
    HttpMethod::Patch,
    "/_minco/ticketing/tickets/{ticketId}/assignment",
    true,
    false,
);

#[rustfmt::skip]
pub const CHANGE_TICKET_ASSIGNMENT_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "changeTicketAssignment",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CHANGE_TICKET_PRIORITY: ContractOperation = ContractOperation::new(
    "changeTicketPriority",
    HttpMethod::Patch,
    "/_minco/ticketing/tickets/{ticketId}/priority",
    true,
    false,
);

#[rustfmt::skip]
pub const CHANGE_TICKET_PRIORITY_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "changeTicketPriority",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CHANGE_TICKET_STATUS: ContractOperation = ContractOperation::new(
    "changeTicketStatus",
    HttpMethod::Patch,
    "/_minco/ticketing/tickets/{ticketId}/status",
    true,
    false,
);

#[rustfmt::skip]
pub const CHANGE_TICKET_STATUS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "changeTicketStatus",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CONSUME_TICKETING_HANDOFF: ContractOperation = ContractOperation::new(
    "consumeTicketingHandoff",
    HttpMethod::Post,
    "/_minco/ticketing/handoffs/exchange",
    false,
    false,
);

#[rustfmt::skip]
pub const CONSUME_TICKETING_HANDOFF_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "consumeTicketingHandoff",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const CREATE_TICKET: ContractOperation = ContractOperation::new(
    "createTicket",
    HttpMethod::Post,
    "/_minco/ticketing/tickets",
    true,
    false,
);

#[rustfmt::skip]
pub const CREATE_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "createTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CREATE_TICKET_FROM_HANDOFF: ContractOperation = ContractOperation::new(
    "createTicketFromHandoff",
    HttpMethod::Post,
    "/_minco/ticketing/tickets/from-handoff",
    false,
    false,
);

#[rustfmt::skip]
pub const CREATE_TICKET_FROM_HANDOFF_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "createTicketFromHandoff",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const CREATE_TICKETING_AGENT_MACRO: ContractOperation = ContractOperation::new(
    "createTicketingAgentMacro",
    HttpMethod::Post,
    "/_minco/ticketing/agent/macros",
    true,
    false,
);

#[rustfmt::skip]
pub const CREATE_TICKETING_AGENT_MACRO_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "createTicketingAgentMacro",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CREATE_TICKETING_CLARIFICATION: ContractOperation = ContractOperation::new(
    "createTicketingClarification",
    HttpMethod::Post,
    "/_minco/ticketing/agent/tickets/{ticketId}/clarifications",
    true,
    false,
);

#[rustfmt::skip]
pub const CREATE_TICKETING_CLARIFICATION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "createTicketingClarification",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const CREATE_TICKETING_REQUESTER_SESSION: ContractOperation = ContractOperation::new(
    "createTicketingRequesterSession",
    HttpMethod::Post,
    "/_minco/ticketing/requester/sessions",
    false,
    false,
);

#[rustfmt::skip]
pub const CREATE_TICKETING_REQUESTER_SESSION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "createTicketingRequesterSession",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const DECIDE_TICKETING_AUTOMATION_PROPOSAL: ContractOperation = ContractOperation::new(
    "decideTicketingAutomationProposal",
    HttpMethod::Patch,
    "/_minco/ticketing/agent/automation-proposals/{proposalId}",
    true,
    false,
);

#[rustfmt::skip]
pub const DECIDE_TICKETING_AUTOMATION_PROPOSAL_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "decideTicketingAutomationProposal",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const END_TICKETING_REQUESTER_SESSION: ContractOperation = ContractOperation::new(
    "endTicketingRequesterSession",
    HttpMethod::Post,
    "/_minco/ticketing/requester/logout",
    true,
    false,
);

#[rustfmt::skip]
pub const END_TICKETING_REQUESTER_SESSION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "endTicketingRequesterSession",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKET: ContractOperation = ContractOperation::new(
    "getTicket",
    HttpMethod::Get,
    "/_minco/ticketing/tickets/{ticketId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKET_AI_CONTEXT: ContractOperation = ContractOperation::new(
    "getTicketAiContext",
    HttpMethod::Get,
    "/_minco/ticketing/tickets/{ticketId}/ai-context",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_TICKET_AI_CONTEXT_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketAiContext",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_BOOTSTRAP: ContractOperation = ContractOperation::new(
    "getTicketingAgentBootstrap",
    HttpMethod::Get,
    "/_minco/ticketing/agent/bootstrap",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_BOOTSTRAP_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingAgentBootstrap",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE: ContractOperation = ContractOperation::new(
    "getTicketingAgentConsole",
    HttpMethod::Get,
    "/_minco/ticketing/agent",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingAgentConsole",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE_SCRIPT: ContractOperation = ContractOperation::new(
    "getTicketingAgentConsoleScript",
    HttpMethod::Get,
    "/_minco/ticketing/agent/console.js",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE_SCRIPT_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingAgentConsoleScript",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE_STYLES: ContractOperation = ContractOperation::new(
    "getTicketingAgentConsoleStyles",
    HttpMethod::Get,
    "/_minco/ticketing/agent/console.css",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_CONSOLE_STYLES_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingAgentConsoleStyles",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_TICKET: ContractOperation = ContractOperation::new(
    "getTicketingAgentTicket",
    HttpMethod::Get,
    "/_minco/ticketing/agent/tickets/{ticketId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_AGENT_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingAgentTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_BOOTSTRAP: ContractOperation = ContractOperation::new(
    "getTicketingBootstrap",
    HttpMethod::Get,
    "/_minco/ticketing/bootstrap",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_BOOTSTRAP_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingBootstrap",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_REQUESTER_TICKET: ContractOperation = ContractOperation::new(
    "getTicketingRequesterTicket",
    HttpMethod::Get,
    "/_minco/ticketing/requester/tickets/{ticketId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_REQUESTER_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingRequesterTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const GET_TICKETING_SUPPORT_ENTRY: ContractOperation = ContractOperation::new(
    "getTicketingSupportEntry",
    HttpMethod::Get,
    "/_minco/ticketing/support-entry.js",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_TICKETING_SUPPORT_ENTRY_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "getTicketingSupportEntry",
    true,
    &[],
    &[
    ],
);

#[rustfmt::skip]
pub const INGEST_TICKET_EXTERNAL_MESSAGE: ContractOperation = ContractOperation::new(
    "ingestTicketExternalMessage",
    HttpMethod::Post,
    "/_minco/ticketing/ingress/messages",
    true,
    false,
);

#[rustfmt::skip]
pub const INGEST_TICKET_EXTERNAL_MESSAGE_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "ingestTicketExternalMessage",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const ISSUE_TICKETING_HANDOFF: ContractOperation = ContractOperation::new(
    "issueTicketingHandoff",
    HttpMethod::Post,
    "/_minco/ticketing/integrations/handoffs",
    true,
    false,
);

#[rustfmt::skip]
pub const ISSUE_TICKETING_HANDOFF_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "issueTicketingHandoff",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_MACROS: ContractOperation = ContractOperation::new(
    "listTicketingAgentMacros",
    HttpMethod::Get,
    "/_minco/ticketing/agent/macros",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_MACROS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingAgentMacros",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_SEARCH: ContractOperation = ContractOperation::new(
    "listTicketingAgentSearch",
    HttpMethod::Get,
    "/_minco/ticketing/agent/search",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_SEARCH_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingAgentSearch",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_TICKETS: ContractOperation = ContractOperation::new(
    "listTicketingAgentTickets",
    HttpMethod::Get,
    "/_minco/ticketing/agent/tickets",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_TICKETS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingAgentTickets",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_VIEW: ContractOperation = ContractOperation::new(
    "listTicketingAgentView",
    HttpMethod::Get,
    "/_minco/ticketing/agent/views/{viewId}",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_AGENT_VIEW_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingAgentView",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_AUTOMATION_PROPOSALS: ContractOperation = ContractOperation::new(
    "listTicketingAutomationProposals",
    HttpMethod::Get,
    "/_minco/ticketing/agent/tickets/{ticketId}/automation-proposals",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_AUTOMATION_PROPOSALS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingAutomationProposals",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_CLARIFICATIONS: ContractOperation = ContractOperation::new(
    "listTicketingClarifications",
    HttpMethod::Get,
    "/_minco/ticketing/agent/tickets/{ticketId}/clarifications",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_CLARIFICATIONS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingClarifications",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_CLARIFICATIONS: ContractOperation = ContractOperation::new(
    "listTicketingRequesterClarifications",
    HttpMethod::Get,
    "/_minco/ticketing/requester/clarifications",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_CLARIFICATIONS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingRequesterClarifications",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_MESSAGES: ContractOperation = ContractOperation::new(
    "listTicketingRequesterMessages",
    HttpMethod::Get,
    "/_minco/ticketing/requester/tickets/{ticketId}/messages",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_MESSAGES_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingRequesterMessages",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_TICKETS: ContractOperation = ContractOperation::new(
    "listTicketingRequesterTickets",
    HttpMethod::Get,
    "/_minco/ticketing/requester/tickets",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETING_REQUESTER_TICKETS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTicketingRequesterTickets",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const LIST_TICKETS: ContractOperation = ContractOperation::new(
    "listTickets",
    HttpMethod::Get,
    "/_minco/ticketing/tickets",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_TICKETS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "listTickets",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const MANAGE_TICKETING_AGENT_TICKET: ContractOperation = ContractOperation::new(
    "manageTicketingAgentTicket",
    HttpMethod::Patch,
    "/_minco/ticketing/agent/tickets/{ticketId}/management",
    true,
    false,
);

#[rustfmt::skip]
pub const MANAGE_TICKETING_AGENT_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "manageTicketingAgentTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REPLACE_TICKETING_KNOWLEDGE_LINKS: ContractOperation = ContractOperation::new(
    "replaceTicketingKnowledgeLinks",
    HttpMethod::Put,
    "/_minco/ticketing/agent/tickets/{ticketId}/knowledge-links",
    true,
    false,
);

#[rustfmt::skip]
pub const REPLACE_TICKETING_KNOWLEDGE_LINKS_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "replaceTicketingKnowledgeLinks",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REPLY_TICKETING_CLARIFICATION: ContractOperation = ContractOperation::new(
    "replyTicketingClarification",
    HttpMethod::Post,
    "/_minco/ticketing/requester/clarifications/{clarificationId}/reply",
    true,
    false,
);

#[rustfmt::skip]
pub const REPLY_TICKETING_CLARIFICATION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "replyTicketingClarification",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REPLY_TO_TICKET_AS_AGENT: ContractOperation = ContractOperation::new(
    "replyToTicketAsAgent",
    HttpMethod::Post,
    "/_minco/ticketing/tickets/{ticketId}/agent-replies",
    true,
    false,
);

#[rustfmt::skip]
pub const REPLY_TO_TICKET_AS_AGENT_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "replyToTicketAsAgent",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REPLY_TO_TICKET_AS_REQUESTER: ContractOperation = ContractOperation::new(
    "replyToTicketAsRequester",
    HttpMethod::Post,
    "/_minco/ticketing/tickets/{ticketId}/requester-replies",
    true,
    false,
);

#[rustfmt::skip]
pub const REPLY_TO_TICKET_AS_REQUESTER_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "replyToTicketAsRequester",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REPLY_TO_TICKETING_REQUESTER_TICKET: ContractOperation = ContractOperation::new(
    "replyToTicketingRequesterTicket",
    HttpMethod::Post,
    "/_minco/ticketing/requester/tickets/{ticketId}/replies",
    true,
    false,
);

#[rustfmt::skip]
pub const REPLY_TO_TICKETING_REQUESTER_TICKET_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "replyToTicketingRequesterTicket",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const REQUEST_TICKETING_AUTOMATION: ContractOperation = ContractOperation::new(
    "requestTicketingAutomation",
    HttpMethod::Post,
    "/_minco/ticketing/agent/tickets/{ticketId}/automation",
    true,
    false,
);

#[rustfmt::skip]
pub const REQUEST_TICKETING_AUTOMATION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "requestTicketingAutomation",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const SEND_TICKETING_CLARIFICATION: ContractOperation = ContractOperation::new(
    "sendTicketingClarification",
    HttpMethod::Post,
    "/_minco/ticketing/agent/clarifications/{clarificationId}/send",
    true,
    false,
);

#[rustfmt::skip]
pub const SEND_TICKETING_CLARIFICATION_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "sendTicketingClarification",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const SUBMIT_TICKETING_CSAT: ContractOperation = ContractOperation::new(
    "submitTicketingCsat",
    HttpMethod::Post,
    "/_minco/ticketing/requester/tickets/{ticketId}/csat",
    true,
    false,
);

#[rustfmt::skip]
pub const SUBMIT_TICKETING_CSAT_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "submitTicketingCsat",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const TRANSFER_TICKET_QUEUE: ContractOperation = ContractOperation::new(
    "transferTicketQueue",
    HttpMethod::Patch,
    "/_minco/ticketing/tickets/{ticketId}/queue",
    true,
    false,
);

#[rustfmt::skip]
pub const TRANSFER_TICKET_QUEUE_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "transferTicketQueue",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub const UPDATE_TICKETING_AGENT_MACRO: ContractOperation = ContractOperation::new(
    "updateTicketingAgentMacro",
    HttpMethod::Patch,
    "/_minco/ticketing/agent/macros/{macroId}",
    true,
    false,
);

#[rustfmt::skip]
pub const UPDATE_TICKETING_AGENT_MACRO_AUTHORIZATION: ContractAuthorizationPolicy = ContractAuthorizationPolicy::new(
    "updateTicketingAgentMacro",
    false,
    &[],
    &[
        ContractAuthorizationAlternative::new(&[]),
    ],
);

#[rustfmt::skip]
pub static OPERATIONS: &[ContractOperation] = &[
    ADD_TICKET_INTERNAL_NOTE,
    CHANGE_TICKET_ASSIGNMENT,
    CHANGE_TICKET_PRIORITY,
    CHANGE_TICKET_STATUS,
    CONSUME_TICKETING_HANDOFF,
    CREATE_TICKET,
    CREATE_TICKET_FROM_HANDOFF,
    CREATE_TICKETING_AGENT_MACRO,
    CREATE_TICKETING_CLARIFICATION,
    CREATE_TICKETING_REQUESTER_SESSION,
    DECIDE_TICKETING_AUTOMATION_PROPOSAL,
    END_TICKETING_REQUESTER_SESSION,
    GET_TICKET,
    GET_TICKET_AI_CONTEXT,
    GET_TICKETING_AGENT_BOOTSTRAP,
    GET_TICKETING_AGENT_CONSOLE,
    GET_TICKETING_AGENT_CONSOLE_SCRIPT,
    GET_TICKETING_AGENT_CONSOLE_STYLES,
    GET_TICKETING_AGENT_TICKET,
    GET_TICKETING_BOOTSTRAP,
    GET_TICKETING_REQUESTER_TICKET,
    GET_TICKETING_SUPPORT_ENTRY,
    INGEST_TICKET_EXTERNAL_MESSAGE,
    ISSUE_TICKETING_HANDOFF,
    LIST_TICKETING_AGENT_MACROS,
    LIST_TICKETING_AGENT_SEARCH,
    LIST_TICKETING_AGENT_TICKETS,
    LIST_TICKETING_AGENT_VIEW,
    LIST_TICKETING_AUTOMATION_PROPOSALS,
    LIST_TICKETING_CLARIFICATIONS,
    LIST_TICKETING_REQUESTER_CLARIFICATIONS,
    LIST_TICKETING_REQUESTER_MESSAGES,
    LIST_TICKETING_REQUESTER_TICKETS,
    LIST_TICKETS,
    MANAGE_TICKETING_AGENT_TICKET,
    REPLACE_TICKETING_KNOWLEDGE_LINKS,
    REPLY_TICKETING_CLARIFICATION,
    REPLY_TO_TICKET_AS_AGENT,
    REPLY_TO_TICKET_AS_REQUESTER,
    REPLY_TO_TICKETING_REQUESTER_TICKET,
    REQUEST_TICKETING_AUTOMATION,
    SEND_TICKETING_CLARIFICATION,
    SUBMIT_TICKETING_CSAT,
    TRANSFER_TICKET_QUEUE,
    UPDATE_TICKETING_AGENT_MACRO,
];
