use crate::{ContractDocument, HttpMethod};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::{collections::BTreeSet, fmt::Write as _};

pub fn generated_contract_digest(source: &str) -> String {
    format!("{:x}", Sha256::digest(source.as_bytes()))
}

pub fn generate_rust(document: &ContractDocument) -> String {
    let mut output = String::new();
    writeln!(
        output,
        "// @generated by minco-contract {}",
        env!("CARGO_PKG_VERSION")
    )
    .expect("writing to String cannot fail");
    writeln!(output, "// Contract SHA-256: {}", document.sha256)
        .expect("writing to String cannot fail");
    output.push_str("// Do not edit manually; run `minco contract sync`.\n\n");
    output.push_str("#[allow(unused_imports)]\nuse chrono::{DateTime, Utc};\n");
    output.push_str("use minco_contract::{ContractOperation, HttpMethod};\n");
    output.push_str("use serde::{Deserialize, Serialize};\n");
    output.push_str("#[allow(unused_imports)]\nuse uuid::Uuid;\n\n");
    if let Some(schemas) = document
        .raw
        .pointer("/components/schemas")
        .and_then(Value::as_object)
    {
        let mut names: Vec<_> = schemas.keys().collect();
        names.sort();
        for name in names {
            output.push_str(&render_schema(name, &schemas[name]));
            output.push('\n');
        }
    }
    for operation in &document.operations {
        let constant = screaming_snake(&operation.operation_id);
        write!(
            output,
            "#[rustfmt::skip]\npub const {constant}: ContractOperation = ContractOperation::new(\n    \"{}\",\n    HttpMethod::{},\n    \"{}\",\n    {},\n    {},\n);\n\n",
            operation.operation_id,
            method_variant(operation.method),
            operation.path,
            operation.authenticated,
            operation.idempotent,
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("#[rustfmt::skip]\npub static OPERATIONS: &[ContractOperation] = &[\n");
    for operation in &document.operations {
        writeln!(output, "    {},", screaming_snake(&operation.operation_id))
            .expect("writing to String cannot fail");
    }
    output.push_str("];\n");
    output
}

fn render_schema(name: &str, schema: &Value) -> String {
    if schema.get("type").and_then(Value::as_str) == Some("string") && schema.get("enum").is_some()
    {
        return render_enum(name, schema);
    }
    if schema.get("type").and_then(Value::as_str) == Some("object") {
        return render_struct(name, schema);
    }
    format!("pub type {name} = {};\n", rust_type(schema, false))
}

fn render_enum(name: &str, schema: &Value) -> String {
    let mut output =
        String::from("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
    writeln!(output, "pub enum {name} {{").expect("writing to String cannot fail");
    for value in schema
        .get("enum")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        if let Some(value) = value.as_str() {
            writeln!(
                output,
                "    #[serde(rename = \"{value}\")]\n    {},",
                pascal_case(value)
            )
            .expect("writing to String cannot fail");
        }
    }
    output.push_str("}\n");
    output
}

fn render_struct(name: &str, schema: &Value) -> String {
    let required: BTreeSet<_> = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect();
    let mut output =
        String::from("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    if schema.get("additionalProperties") == Some(&Value::Bool(false)) {
        output.push_str("#[serde(deny_unknown_fields)]\n");
    }
    writeln!(output, "pub struct {name} {{").expect("writing to String cannot fail");
    if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
        let mut names: Vec<_> = properties.keys().collect();
        names.sort();
        for property_name in names {
            let rust_name = rust_field_name(property_name);
            if rust_name != *property_name {
                writeln!(output, "    #[serde(rename = \"{property_name}\")]")
                    .expect("writing to String cannot fail");
            }
            let is_required = required.contains(property_name.as_str());
            if !is_required {
                output
                    .push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
            }
            writeln!(
                output,
                "    pub {rust_name}: {},",
                rust_type(&properties[property_name], !is_required)
            )
            .expect("writing to String cannot fail");
        }
    }
    output.push_str("}\n");
    output
}

fn rust_type(schema: &Value, optional: bool) -> String {
    let nullable = schema
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|value| value.as_str() == Some("null")));
    let base = if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        reference
            .rsplit('/')
            .next()
            .unwrap_or("serde_json::Value")
            .to_owned()
    } else if schema.get("type").and_then(Value::as_str) == Some("array") {
        format!(
            "Vec<{}>",
            rust_type(schema.get("items").unwrap_or(&Value::Null), false)
        )
    } else {
        match schema.get("type").and_then(Value::as_str) {
            Some("string") => match schema.get("format").and_then(Value::as_str) {
                Some("date-time") => "DateTime<Utc>".to_owned(),
                Some("uuid") => "Uuid".to_owned(),
                _ => "String".to_owned(),
            },
            Some("integer") => {
                if schema.get("format").and_then(Value::as_str) == Some("int32") {
                    "i32".to_owned()
                } else {
                    "i64".to_owned()
                }
            }
            Some("number") => "f64".to_owned(),
            Some("boolean") => "bool".to_owned(),
            Some("object") => "serde_json::Value".to_owned(),
            _ => {
                if let Some(types) = schema.get("type").and_then(Value::as_array) {
                    let non_null = types
                        .iter()
                        .filter_map(Value::as_str)
                        .find(|value| *value != "null")
                        .unwrap_or("object");
                    rust_type(
                        &serde_json::json!({"type": non_null, "format": schema.get("format")}),
                        false,
                    )
                } else {
                    "serde_json::Value".to_owned()
                }
            }
        }
    };
    if optional || nullable {
        format!("Option<{base}>")
    } else {
        base
    }
}

const fn method_variant(method: HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "Get",
        HttpMethod::Post => "Post",
        HttpMethod::Put => "Put",
        HttpMethod::Patch => "Patch",
        HttpMethod::Delete => "Delete",
        HttpMethod::Options => "Options",
        HttpMethod::Head => "Head",
    }
}

fn screaming_snake(value: &str) -> String {
    snake_case(value).to_ascii_uppercase()
}

fn rust_field_name(value: &str) -> String {
    let mut identifier = snake_case(value);
    if identifier.is_empty() {
        identifier.push_str("field");
    }
    if identifier
        .as_bytes()
        .first()
        .is_some_and(u8::is_ascii_digit)
    {
        identifier.insert(0, '_');
    }
    if is_rust_keyword(&identifier) {
        format!("r#{identifier}")
    } else {
        identifier
    }
}

fn snake_case(value: &str) -> String {
    let mut output = String::new();
    let mut previous_was_separator = false;
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_uppercase() {
            if index > 0 && !previous_was_separator {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if character.is_ascii_alphanumeric() || character == '_' {
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !output.is_empty() && !previous_was_separator {
            output.push('_');
            previous_was_separator = true;
        }
    }
    while output.ends_with('_') {
        output.pop();
    }
    output
}

fn pascal_case(value: &str) -> String {
    let mut output = value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>();
    if output.is_empty() {
        output.push_str("Value");
    } else if output.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        output.insert_str(0, "Value");
    }
    output
}

fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn names_are_deterministic() {
        assert_eq!(snake_case("placeOrder"), "place_order");
        assert_eq!(screaming_snake("placeOrder"), "PLACE_ORDER");
        assert_eq!(pascal_case("in-progress"), "InProgress");
        assert_eq!(rust_field_name("type"), "r#type");
        assert_eq!(rust_field_name("request.id"), "request_id");
        assert_eq!(rust_field_name("3d"), "_3d");
    }
}
