// @generated by minco-contract 1.5.0
// Contract SHA-256: f43837b7e41a03b311588dd5466f7029d4bf1e8940685bd194bc1bc97abd796c
// Do not edit manually; run `minco contract sync`.

#[allow(unused_imports)]
use chrono::{DateTime, Utc};
use minco_contract::{ContractOperation, HttpMethod};
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CursorPageInfo {
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    #[serde(rename = "nextCursor")]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DependencyHealth {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    pub ready: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LivenessResponse {
    pub live: bool,
    pub service: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderAuditActor {
    pub kind: String,
    pub subject: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderAuditChange {
    pub after: Option<String>,
    pub before: Option<String>,
    pub field: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderAuditCollection {
    pub data: Vec<OrderAuditEvent>,
    pub page: CursorPageInfo,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderAuditEvent {
    pub action: String,
    pub actor: OrderAuditActor,
    pub changes: Vec<OrderAuditChange>,
    #[serde(rename = "correlationId")]
    pub correlation_id: Uuid,
    #[serde(rename = "eventId")]
    pub event_id: Uuid,
    #[serde(rename = "occurredAt")]
    pub occurred_at: DateTime<Utc>,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(rename = "recordedAt")]
    pub recorded_at: DateTime<Utc>,
    #[serde(rename = "resourceRevision")]
    pub resource_revision: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderCollection {
    pub data: Vec<OrderResponse>,
    pub page: CursorPageInfo,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderDocument {
    pub data: OrderResponse,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderLineResponse {
    pub quantity: i32,
    pub sku: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderResponse {
    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,
    #[serde(rename = "customerReference")]
    pub customer_reference: String,
    pub id: Uuid,
    pub lines: Vec<OrderLineResponse>,
    pub revision: i64,
    pub status: OrderStatus,
    #[serde(rename = "updatedAt")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlaceOrderLineRequest {
    pub quantity: i64,
    pub sku: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlaceOrderRequest {
    #[serde(rename = "customerReference")]
    pub customer_reference: String,
    pub lines: Vec<PlaceOrderLineRequest>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProblemDetails {
    pub code: String,
    pub detail: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub errors: Option<serde_json::Value>,
    #[serde(rename = "requestId")]
    pub request_id: String,
    pub status: i32,
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReadinessResponse {
    pub dependencies: serde_json::Value,
    pub ready: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateOrderRequest {
    #[serde(rename = "customerReference")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_reference: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lines: Option<Vec<PlaceOrderLineRequest>>,
}

#[rustfmt::skip]
pub const DELETE_ORDER: ContractOperation = ContractOperation::new(
    "deleteOrder",
    HttpMethod::Delete,
    "/orders/{orderId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_LIVE: ContractOperation = ContractOperation::new(
    "getLive",
    HttpMethod::Get,
    "/health/live",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_ORDER: ContractOperation = ContractOperation::new(
    "getOrder",
    HttpMethod::Get,
    "/orders/{orderId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_READY: ContractOperation = ContractOperation::new(
    "getReady",
    HttpMethod::Get,
    "/health/ready",
    false,
    false,
);

#[rustfmt::skip]
pub const LIST_ORDER_AUDIT_HISTORY: ContractOperation = ContractOperation::new(
    "listOrderAuditHistory",
    HttpMethod::Get,
    "/orders/{orderId}/audit",
    true,
    false,
);

#[rustfmt::skip]
pub const LIST_ORDERS: ContractOperation = ContractOperation::new(
    "listOrders",
    HttpMethod::Get,
    "/orders",
    true,
    false,
);

#[rustfmt::skip]
pub const PLACE_ORDER: ContractOperation = ContractOperation::new(
    "placeOrder",
    HttpMethod::Post,
    "/orders",
    true,
    true,
);

#[rustfmt::skip]
pub const UPDATE_ORDER: ContractOperation = ContractOperation::new(
    "updateOrder",
    HttpMethod::Patch,
    "/orders/{orderId}",
    true,
    false,
);

#[rustfmt::skip]
pub static OPERATIONS: &[ContractOperation] = &[
    DELETE_ORDER,
    GET_LIVE,
    GET_ORDER,
    GET_READY,
    LIST_ORDER_AUDIT_HISTORY,
    LIST_ORDERS,
    PLACE_ORDER,
    UPDATE_ORDER,
];
