// @generated by minco-contract 0.3.0
// Contract SHA-256: 84e48fb8460a6000e4055de391b8cb00f0e17f60df465967207a50bd7d7b910e
// Do not edit manually; run `minco contract sync`.

#[allow(unused_imports)]
use chrono::{DateTime, Utc};
use minco_contract::{ContractOperation, HttpMethod};
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DependencyHealth {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    pub ready: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LivenessResponse {
    pub live: bool,
    pub service: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderLineResponse {
    pub quantity: i32,
    pub sku: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderResponse {
    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,
    #[serde(rename = "customerReference")]
    pub customer_reference: String,
    pub id: Uuid,
    pub lines: Vec<OrderLineResponse>,
    pub status: OrderStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlaceOrderLineRequest {
    pub quantity: i64,
    pub sku: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlaceOrderRequest {
    #[serde(rename = "customerReference")]
    pub customer_reference: String,
    pub lines: Vec<PlaceOrderLineRequest>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlaceOrderResponse {
    pub order: OrderResponse,
    pub replayed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProblemDetails {
    pub code: String,
    pub detail: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub errors: Option<serde_json::Value>,
    #[serde(rename = "requestId")]
    pub request_id: String,
    pub status: i32,
    pub title: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReadinessResponse {
    pub dependencies: serde_json::Value,
    pub ready: bool,
}

#[rustfmt::skip]
pub const GET_LIVE: ContractOperation = ContractOperation::new(
    "getLive",
    HttpMethod::Get,
    "/health/live",
    false,
    false,
);

#[rustfmt::skip]
pub const GET_ORDER: ContractOperation = ContractOperation::new(
    "getOrder",
    HttpMethod::Get,
    "/orders/{orderId}",
    true,
    false,
);

#[rustfmt::skip]
pub const GET_READY: ContractOperation = ContractOperation::new(
    "getReady",
    HttpMethod::Get,
    "/health/ready",
    false,
    false,
);

#[rustfmt::skip]
pub const PLACE_ORDER: ContractOperation = ContractOperation::new(
    "placeOrder",
    HttpMethod::Post,
    "/orders",
    true,
    true,
);

#[rustfmt::skip]
pub static OPERATIONS: &[ContractOperation] = &[
    GET_LIVE,
    GET_ORDER,
    GET_READY,
    PLACE_ORDER,
];
