[package]
name = "orders-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = ["memory"]
memory = []
postgres = ["dep:minco-sqlx-postgres", "dep:sqlx", "sqlx/postgres"]
sqlite = ["dep:minco-sqlx-sqlite", "dep:sqlx", "sqlx/sqlite"]
dynamodb = ["dep:aws-sdk-dynamodb", "dep:minco-aws-dynamodb", "dep:sha2", "dep:tokio"]
all-databases = ["dynamodb", "postgres", "sqlite"]

[dependencies]
async-trait.workspace = true
aws-sdk-dynamodb = { workspace = true, optional = true }
chrono.workspace = true
futures.workspace = true
minco-aws-dynamodb = { workspace = true, optional = true }
minco-core.workspace = true
minco-plugin-audit.workspace = true
minco-sqlx-postgres = { workspace = true, optional = true }
minco-sqlx-sqlite = { workspace = true, optional = true }
orders-application.workspace = true
orders-domain.workspace = true
serde_json.workspace = true
sha2 = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
