[package]
name = "orders-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = ["memory"]
memory = []
postgres = ["dep:minco-sqlx-postgres"]
sqlite = ["dep:minco-sqlx-sqlite"]
all-databases = ["postgres", "sqlite"]

[dependencies]
async-trait.workspace = true
chrono.workspace = true
minco-sqlx-postgres = { workspace = true, optional = true }
minco-sqlx-sqlite = { workspace = true, optional = true }
orders-application.workspace = true
orders-domain.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
